# Generated by Django 3.2.19 on 2023-06-04 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredientrecipe',
            name='unique_recipe_ingredient',
        ),
    ]
